Message.create(content: "Hello, welcome to GreetingsApp!")
Message.create(content: "Hi there! Enjoy your day.")
Message.create(content: "Greetings! How can I assist you?")
Message.create(content: "Hey, nice to see you!")
Message.create(content: "Welcome! Have a great time!")
